name: spoonshare
description: "Meals of Grace."
publish_to: 'none'  # This package is not for publishing
version: 1.2.0

environment:
  sdk: '>=3.2.4 <4.0.0'  # Specify Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  # iOS style icons for Flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.2.2  # Persistent storage for simple data
  flutter_dotenv: ^5.1.0  # Load environment variables from .env file
  google_sign_in: ^6.2.1
  persistent_bottom_nav_bar: ^5.0.2  # Persistent bottom navigation bar
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  permission_handler: ^11.2.0  # Request and check permissions
  flutter_launcher_icons: ^0.13.1  # Generate app launcher icons
  device_info_plus: ^9.1.1  # Get device information
  url_launcher: ^6.2.3  # Launch URLs in a browser or other app
  intl: ^0.19.0  # Internationalization and localization support
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.6  # HTTP client for making requests
  uuid: ^4.3.3  # Generate UUIDs
  geocoding: ^2.1.1
  custom_info_window: ^1.0.1
  geolocator: ^11.0.0  # Geolocation plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Linting rules for Flutter

flutter:
  uses-material-design: true  # Use Material Design icons

  assets:
    - assets/images/  # Directory for image assets

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf  # Regular style font

    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 700  # Bold style font

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/spoonshare_launcher.png"
  min_sdk_android: 21  # Minimum SDK version for Android
  web:
    generate: true
    image_path: "assets/images/spoonshare_launcher.png"
    background_color: "#FFFFFF"  # Replace with your background color
    theme_color: "#000000"      # Replace with your theme color
